version: '3.8'
services:
  pgdatabase:
    container_name: pgdatabase_container
    image: postgres:14.5
    platform: linux/amd64
    env_file:
      - ./.env

    ports:
      - "5432:5432"

    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data

  fastapi:
    container_name: fastapi_container
    image: projectdim.org/fastapi:${version:-latest}
    build:
      target: prod
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env

    ports:
      # By default, exposes 7000 on the host
      - "${SERVER_HOST_PORT:-7000}:7000"
    depends_on:
      pgdatabase:
        condition: service_healthy

volumes:
  pg-data: