"""organization disabled/activated

Revision ID: 100677e079fc
Revises: cd1e240a1aff
Create Date: 2023-02-06 21:14:36.855808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100677e079fc'
down_revision = 'cd1e240a1aff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('organization', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('organization', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('organization', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'disabled')
    op.drop_column('organization', 'activated')
    op.drop_column('organization', 'updated_at')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
