"""oauth

Revision ID: 76b150754966
Revises: 6a7b4cfef54c
Create Date: 2023-01-21 14:05:58.627351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b150754966'
down_revision = '6a7b4cfef54c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauthrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verbose_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verbose_name')
    )
    op.create_index(op.f('ix_oauthrole_id'), 'oauthrole', ['id'], unique=False)
    op.create_table('oauthscope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope')
    )
    op.create_index(op.f('ix_oauthscope_id'), 'oauthscope', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_oauthscope_id'), table_name='oauthscope')
    op.drop_table('oauthscope')
    op.drop_index(op.f('ix_oauthrole_id'), table_name='oauthrole')
    op.drop_table('oauthrole')
    # ### end Alembic commands ###
