"""Changelog submitted_by

Revision ID: 9d20fe4a7ff7
Revises: cae2891def63
Create Date: 2023-02-10 11:25:46.675839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d20fe4a7ff7'
down_revision = 'cae2891def63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('changelog', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('changelog', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'changelog', 'user', ['submitted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'changelog', type_='foreignkey')
    op.drop_column('changelog', 'submitted_by')
    op.drop_column('changelog', 'updated_at')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
