name: CI checks
run-name: Pull request validation
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, prod]

jobs:
  lint:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    container:
      image: python:3.8-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --upgrade pip &&  pip install black

      - name: Run formatting check
        run: black --check ./

      - name: Shutdown
        run: echo "Brilliant!"
